name: Checkout locally on commit
env:
  TARGET_FOLDER: /home/vanya/junk

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  ckout:
    runs-on: work-laptop
    steps:
    - name: Check if directory already exists and remove it
      run: |
        if [ -d ${{env.TARGET_FOLDER}} ]; then rm -Rf ${{env.TARGET_FOLDER}}; fi
        echo ${{env.TARGET_FOLDER}}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Move the code
      run: |
        cp $GITHUB_WORKSPACE ${{env.TARGET_FOLDER}}

      
