name: Checkout locally on commit
env:
  GITHUB_WORKSPACE: /home/vanya/junk/
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  ckout:
    runs-on: work-laptop
    steps:
    - name: Check if directory already exists and rm it
      run: if [ -d "$GITHUB_WORKSPACE" ]; then rm -Rf "$GITHUB_WORKSPACE"; fi

    - name: Checkout code
      uses: actions/checkout@v4

      
    # - name: Copy code to destination
    #   run: cp -TRv ./ /home/vanya/junk/
      
