name: Checkout locally on commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  ckout:
    runs-on: work-laptop
    steps:
    - name: Checkout code
      env:
        GITHUB_WORKSPACE: /home/vanya/junk/
      uses: actions/checkout@v4

      
    # - name: Copy code to destination
    #   run: cp -TRv ./ /home/vanya/junk/
      
