name: Checkout locally on commit
env:
  TARGET_FOLDER: /home/vanya/junk

on:
  push:
    branches: [ "master" ]

 
jobs:
  PullChanges:
    runs-on: work-laptop
    steps:
    - name: Git pull
      working-directory: ${{env.TARGET_FOLDER}}
      run: |
        pwd
        git reset --hard
        git clean -fd
        git pull
        
        
      
