name: Checkout locally on commit
env:
  TARGET_FOLDER: /home/vanya/junk

on:
  push:
    branches: [ "master" ]

 
jobs:
  PullChanges:
    runs-on: work-laptop
    steps:
      - uses: actions/checkout@v2
      
      - name: Clean the folder
        working-directory: ${{env.TARGET_FOLDER}}
        env:
          USERNAME: vanya-02
          TOKEN: FrrbhwBeWBl2feEwwwUhNTQf7jGFFO17LyCt
        run: |
          pwd
          git reset --hard
          git clean -fd
          git pull
          
          
        
      
