name: Checkout locally on commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
 
jobs:
  ckout:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Copy code to destination
      run: cp -TRv ./ /home/vanya/Documents/junk/
      
