name: Checkout locally on commit
env:
  TARGET_FOLDER: /home/vanya/k8

on:
  push:
    branches: [ "master" ]

 
jobs:
  PullChanges:
    runs-on: work-laptop
    steps:   
      - name: Clean the folder
        working-directory: ${{env.TARGET_FOLDER}}
        run: |
          pwd
          git reset --hard
          git clean -fd
      - name: Pull new changes
        working-directory: ${{env.TARGET_FOLDER}}
        run: |
          pwd
          git pull  https://${{secrets.PAT}}@github.com/vanya-02/k8.git
        
          
          
        
      
