name: Checkout locally on commit
env:
  TARGET_FOLDER: /home/vanya/junk

on:
  push:
    branches: [ "master" ]

 
jobs:
  ckout:
    runs-on: work-laptop
    steps:
    - name: dd
      working-directory: <TARGET_FOLDER>
      run: |
        pwd
        git reset --hard
        
      
